# -*- coding: utf-8 -*-
"""Copy of MotionTrackingAlgorithm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xee2GklzRK8Wq4ApkPyMXEvSR4oU6CKM

# Regression: Predicting final location of a point on an origami robot

These models aim to predict the x, y, and z points of a point on an origami robot after movement. These models allow for positioning and movement calculation before doing expiriments to allow for precise motions
"""

import pathlib

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

! pip install git+https://github.com/tensorflow/docs
import tensorflow_docs as tfdocs
import tensorflow_docs.plots
import tensorflow_docs.modeling

from google.colab import drive
drive.mount("/content/gdrive")

from tensorflow.keras.callbacks import ReduceLROnPlateau

"""## Motion Tracked Dataset

The dataset is made using a motion tracking system and saving the coordinates of maximum distance for a marker on an origami robot.


"""

Train_dataset = pd.read_csv('/content/gdrive/My Drive/ECE528/Final/Data.csv')

"""Import it using pandas"""

column_names = ['D1','D2','H1','Motordist','Xmax',
                'Ymax', 'Zmax']
raw_dataset = pd.read_csv('/content/gdrive/My Drive/ECE528/Final/Data.csv', names=column_names,
                      na_values = "?", comment='\t',
                      sep=",", skipinitialspace=True, skiprows=1)

dataset = raw_dataset.copy()
dataset.tail()

"""### Splitting data into train and test

"""

train_dataset = dataset.sample(frac=0.95,random_state=0)
test_dataset = dataset.drop(train_dataset.index)

"""### Split features from labels

Separate the target value, or "label", from the features. This label is the value that you will train the model to predict.
"""

train_labelsD1 = (train_dataset.pop('D1'))
train_labelsD2 = (train_dataset.pop('D2'))
train_labelsH1 = (train_dataset.pop('H1'))
train_labelsMdist = (train_dataset.pop('Motordist'))
test_labelsD1 = (test_dataset.pop('D1'))
test_labelsD2 = (test_dataset.pop('D2'))
test_labelsH1 = (test_dataset.pop('H1'))
test_labelsMdist = (test_dataset.pop('Motordist'))

"""## The model"""

modelD1 = keras.Sequential([
    keras.layers.Dense(256, activation='relu', input_shape=[len(train_dataset.keys())]),
    keras.layers.BatchNormalization(center=True, scale=False),
    keras.layers.Dropout(.4),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.BatchNormalization(center=True, scale=False),
    keras.layers.Dropout(.2),

    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(1),

 ])


modelD1.compile(optimizer=keras.optimizers.Adam(learning_rate=.001), loss='mse', metrics=['mae','mse', 'accuracy'])

modelD2 = keras.Sequential([
    keras.layers.Dense(256, activation='relu', input_shape=[len(train_dataset.keys())]),
    keras.layers.BatchNormalization(center=True, scale=False),
    keras.layers.Dropout(.4),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.BatchNormalization(center=True, scale=False),
    keras.layers.Dropout(.2),

    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(1),

 ])


modelD2.compile(optimizer=keras.optimizers.Adam(learning_rate=.001), loss='mse', metrics=['mae','mse','accuracy'])

modelH1 = keras.Sequential([
    keras.layers.Dense(256, activation='relu', input_shape=[len(train_dataset.keys())]),
    keras.layers.BatchNormalization(center=True, scale=False),
    keras.layers.Dropout(.4),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.BatchNormalization(center=True, scale=False),
    keras.layers.Dropout(.2),

    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(1),

 ])


modelH1.compile(optimizer=keras.optimizers.Adam(learning_rate=.001), loss='mse', metrics=['mae','mse','accuracy'])

modelMDist = keras.Sequential([
    keras.layers.Dense(256, activation='relu', input_shape=[len(train_dataset.keys())]),
    keras.layers.BatchNormalization(center=True, scale=False),
    keras.layers.Dropout(.4),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.BatchNormalization(center=True, scale=False),
    keras.layers.Dropout(.2),

    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(1),

 ])


modelMDist.compile(optimizer=keras.optimizers.Adam(learning_rate=.001), loss='mse', metrics=['mae','mse','accuracy'])

len(train_dataset.keys())

learning_rate_reduce = ReduceLROnPlateau(monitor='mae', patience = 200, verbose=1,factor=0.5, min_lr=0.00001)

"""### Train the model

Train the model for 1000 epochs, and record the training and validation accuracy in the `history` object.
"""

EPOCHS = 5000
early_stop = keras.callbacks.EarlyStopping(monitor='mae',patience=500)

historyx = modelD1.fit(
  train_dataset, train_labelsD1,
  epochs=EPOCHS, validation_split = 0.2, verbose=0,
  callbacks=[learning_rate_reduce, early_stop, tfdocs.modeling.EpochDots()])

EPOCHS = 5000
early_stop = keras.callbacks.EarlyStopping(monitor='mae',patience=500)

historyy = modelD2.fit(
  train_dataset, train_labelsD2,
  epochs=EPOCHS, validation_split = 0.2, verbose=0,
  callbacks=[learning_rate_reduce, early_stop, tfdocs.modeling.EpochDots()])

EPOCHS = 5000

historyz = modelH1.fit(
  train_dataset, train_labelsH1,
  epochs=EPOCHS, validation_split = 0.2, verbose=0,
  callbacks=[learning_rate_reduce, early_stop, tfdocs.modeling.EpochDots()])

EPOCHS = 5000

historyMdist = modelMDist.fit(
  train_dataset, train_labelsMdist,
  epochs=EPOCHS, validation_split = 0.2, verbose=0,
  callbacks=[learning_rate_reduce, early_stop, tfdocs.modeling.EpochDots()])

"""Visualize the model's training progress using the stats stored in the `history` object."""

plotter = tfdocs.plots.HistoryPlotter(smoothing_std=2)

plotter.plot({'Basic': historyx}, metric = "mae")
plt.ylim([0, .5])
plt.ylabel('MAE [m]')

plotter.plot({'Basic': historyy}, metric = "mae")
plt.ylim([0, .5])
plt.ylabel('MAE [m]')

plotter.plot({'Basic': historyz}, metric = "mae")
plt.ylim([0, .5])
plt.ylabel('MAE [m]')

"""# Generalizing data test"""

loss, mae, mse, accuracy = modelD1.evaluate(test_dataset, test_labelsD1, verbose=2)

print("Testing set Mean Abs Error: {:5.5f} m".format(mae))

loss, mae, mse, accuracy = modely.evaluate(test_dataset, test_labelsy, verbose=2)

print("Testing set Mean Abs Error: {:5.5f} m".format(mae))

loss, mae, mse, accuracy = modelz.evaluate(test_dataset, test_labelsz, verbose=2)

print("Testing set Mean Abs Error: {:5.5f} m".format(mae))

"""# Testing predictions and comparing

## X predictions (in meters)
"""

PredictionD1=modelD1.predict(test_dataset)

PredictionD1

test_labelsD1

"""## Y predictions (in meters)"""

Predictiony=modely.predict(test_dataset)

Predictiony

test_labelsy

"""## Z predictions (in meters)"""

Predictionz=modelz.predict(test_dataset)

Predictionz

test_labelsz

"""# Saving models and compressing:"""

modelx.save_weights('/content/gdrive/My Drive/ECE528/Final/ModelWeights/modelx_weights')

modely.save_weights('/content/gdrive/My Drive/ECE528/Final/ModelWeights/modely_weights')

modelz.save_weights('/content/gdrive/My Drive/ECE528/Final/ModelWeights/modelz_weights')

"""## Pruning"""

import os
import zipfile
import pathlib

! pip install -q tensorflow-model-optimization
import tensorflow_model_optimization as tfmot

converterx = tf.lite.TFLiteConverter.from_keras_model(modelx)
tflite_modelx = converterx.convert()

import pathlib

tflite_model_filesx = pathlib.Path('/content/gdrive/My Drive/ECE528/Final/tflite_modelx.tflite')
tflite_model_filesx.write_bytes(tflite_modelx)

convertery = tf.lite.TFLiteConverter.from_keras_model(modely)
tflite_modely = convertery.convert()

tflite_model_filesy = pathlib.Path('/content/gdrive/My Drive/ECE528/Final/tflite_modely.tflite')
tflite_model_filesy.write_bytes(tflite_modely)

converterz = tf.lite.TFLiteConverter.from_keras_model(modelz)
tflite_modelz = converterz.convert()

tflite_model_filesz = pathlib.Path('/content/gdrive/My Drive/ECE528/Final/tflite_modelz.tflite')
tflite_model_filesz.write_bytes(tflite_modelz)